version: "3.6"
services:
  postgres:
    image: postgres:14.1
    container_name: postgres
    hostname: postgres
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bdjuno
    volumes:
      - /tmp/postgres/data:/var/lib/postgresql/data
      - ../../database/schema:/bdjuno/database/schema